kind: pipeline
name: default

platform:
  os: linux
  arch: amd64
clone:
  depth: 1

steps:
- name: build
  image: menny/android_bazel:1.10.0
  environment:
    TERM: dumb
  commands:
  - bazel build //...

- name: test
  image: menny/android_bazel:1.10.0
  commands:
  - bazel test //...

- name: verify_rules_generation
  image: menny/android_bazel:1.10.0
  commands:
    - bazel run //resolver:main_deps
    - bazel run //resolver:main_deps

- name: build-examples
  image: menny/android_bazel:1.10.0
  environment:
    TERM: dumb
  commands:
    - (cd examples/plain_java/ ; bazel build //...)
    - (cd examples/java_plugin/ ; bazel build //...)
    - (cd examples/android/ ; bazel build //...)
    - (cd examples/kotlin/ ; bazel build //...)

- name: regenerate-examples
  image: menny/android_bazel:1.10.0
  environment:
    TERM: dumb
  commands:
    - (cd examples/plain_java/ ; bazel run //program:main_deps ; bazel build //...)
    - (cd examples/java_plugin/ ; bazel run //program:main_deps ; bazel build //...)
    - (cd examples/android/ ; bazel run //program:main_deps ; bazel build //...)
    - (cd examples/kotlin/ ; bazel run //program:main_deps ; bazel build //...)

