kind: pipeline
name: default

platform:
  os: linux
  arch: amd64
clone:
  depth: 1

steps:
- name: build
  image: menny/android_bazel:1.10.1
  environment:
    TERM: dumb
  commands:
    - bazel build $(bazel query 'attr(visibility, "//visibility:public", //...)')

- name: test
  image: menny/android_bazel:1.10.1
  commands:
    - bazel test --build_tests_only //...
    - bazel coverage --build_tests_only //...
    - curl -s https://codecov.io/bash > .codecov
    - chmod +x .codecov
    - ./.codecov -t bb45a5d9-b124-469b-a8ce-695b54a0ce12 -s "bazel-out/" -G "**/coverage.dat"

- name: verify_rules_generation
  image: menny/android_bazel:1.10.0
  commands:
    - bazel run //resolver:main_deps
    - bazel run //resolver:main_deps

- name: build-examples
  image: menny/android_bazel:1.10.1
  environment:
    TERM: dumb
  commands:
    - (cd examples/plain_java/ ; bazel build //...)
    - (cd examples/java_plugin/ ; bazel build //...)
    - (cd examples/android/ ; bazel build //...)
    - (cd examples/kotlin/ ; bazel build //...)

- name: regenerate-examples
  image: menny/android_bazel:1.10.1
  environment:
    TERM: dumb
  commands:
    - (cd examples/plain_java/ ; bazel run //program:main_deps ; bazel build //...)
    - (cd examples/java_plugin/ ; bazel run //program:main_deps ; bazel build //...)
    - (cd examples/android/ ; bazel run //program:main_deps ; bazel build //...)
    - (cd examples/kotlin/ ; bazel run //program:main_deps ; bazel build //...)

