name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  checks:
    runs-on: ubuntu-18.04
    container: menny/android_bazel:1.13.7
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        run: ./scripts/ci_build.sh
      - name: test
        run: ./scripts/ci_test.sh
      - name: verify-rules-generation
        run: ./scripts/ci_verify_rules_generation.sh
  examples:
    runs-on: ubuntu-18.04
    needs: [checks]
    container: menny/android_bazel:1.13.7
    strategy:
      matrix:
        example_name: [plain_java, java_plugin, android, kotlin, kotlin_with_kt_rules]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build-examples
        run: ./scripts/ci_build_examples.sh ${{ matrix.example_name }}
      - name: regenerate-examples
        run: ./scripts/ci_regenerate_examples.sh ${{ matrix.example_name }}
